config/routes.rb
  Rails.application.routes.draw do

  resources :packages do
    patch :activate, on: :member
    patch :deactivate, on: :member
  end

  resources :url_exclusions

  root 'packages#index'

  get 'packages/index'

  get 'webauth/login' => 'authentication#login', as: :login
  get 'webauth/logout' => 'authentication#logout', as: :logout

end

app/models/authorized_user.rb
###
# User for authentication and authorization
###
class AuthorizedUser < ActiveRecord::Base
  self.table_name = 'authorized_user'
end

app/models/package.rb
###
#  Class to connect to the VND_PACKAGES table
###
class Package < ActiveRecord::Base
  self.table_name = 'vnd_packages'
  self.primary_key = 'record_id'

  validates :record_id, uniqueness: true
  validates :package_name, :vendor_name, :data_pickup_type, :package_status, presence: true
end

app/models/url_exclusion.rb
# URL Exclusion model
class UrlExclusion < ActiveRecord::Base
  validates :url_substring, length: { minimum: 1 }
end

app/controllers/application_controller.rb
##
# Application Controller for eloader-pkg-admin app
##
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= begin
      AuthorizedUser.find_by(sunet_id: sunet_id)
    end
  end
  helper_method :current_user

  def sunet_id
    request.env['REMOTE_USER'] || ENV['REMOTE_USER']
  end
  helper_method :sunet_id

  def page_title
    'E-Loader Package Admin'
  end
end

app/controllers/authentication_controller.rb
###
#  Controller for handling login/logout and redirecting with flash messages.
###
class AuthenticationController < ApplicationController
  def login
    flash[:success] = 'You have been successfully logged in.'
    redirect_to params[:referrer] || :back
  end

  def logout
    flash[:notice] = 'You have been successfully logged out.'
    redirect_to params[:referrer] || :back
  end
end

app/controllers/packages_controller.rb
##
# Package controller for eloader-pkg-admin app
##
class PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy, :activate, :deactivate]

  def page_title
    'Electronic resource package management'
  end

  # GET /packages
  # GET /packages.json
  def index
    @packages = Package.all
  end

  # GET /packages/1
  # GET /packages/1.json
  def show
  end

  # GET /packages/new
  def new
    @package = Package.new
  end

  # GET /packages/1/edit
  def edit
  end

  # POST /packages
  # POST /packages.json
  def create
    @package = Package.new(package_params)
    respond_to do |format|
      if @package.save
        format.html { redirect_to @package }
        flash[:success] = 'Package was successfully created.'
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1
  # PATCH/PUT /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to @package }
        flash[:success] = 'Package was successfully updated.'
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate
    @package.update(package_status: 'Active')
    redirect_to packages_path
    flash[:success] = 'Package activated.'
  end

  def deactivate
    @package.update(package_status: 'Inactive')
    redirect_to packages_path
    flash[:warning] = 'Package deactivated.'
  end

  # # DELETE /packages/1
  # # DELETE /packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to @package, notice: 'Package was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_package
    @package = Package.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def package_params
    params.require(:package).permit!
  end
end

app/controllers/url_exclusions_controller.rb
# UrlExclusions controller
class UrlExclusionsController < ApplicationController
  before_action :set_url_exclusion, only: [:show, :edit, :update, :destroy]

  def page_title
    'URLs to remove from vendor records'
  end

  # GET /url_exclusions
  # GET /url_exclusions.json
  def index
    @url_exclusions = UrlExclusion.all
  end

  # GET /url_exclusions/1
  # GET /url_exclusions/1.json
  def show
  end

  # GET /url_exclusions/new
  def new
    @url_exclusion = UrlExclusion.new
  end

  # GET /url_exclusions/1/edit
  def edit
  end

  # POST /url_exclusions
  # POST /url_exclusions.json
  def create
    @url_exclusion = UrlExclusion.new(url_exclusion_params)

    respond_to do |format|
      if @url_exclusion.save
        format.html { redirect_to url_exclusions_url, notice: 'Url exclusion was successfully created.' }
        format.json { render :show, status: :created, location: @url_exclusion }
      else
        format.html { render :new }
        format.json { render json: @url_exclusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /url_exclusions/1
  # PATCH/PUT /url_exclusions/1.json
  def update
    respond_to do |format|
      if @url_exclusion.update(url_exclusion_params)
        format.html { redirect_to url_exclusions_url, notice: 'Url exclusion was successfully updated.' }
        format.json { render :show, status: :ok, location: @url_exclusion }
      else
        format.html { render :edit }
        format.json { render json: @url_exclusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /url_exclusions/1
  # DELETE /url_exclusions/1.json
  def destroy
    @url_exclusion.destroy
    respond_to do |format|
      format.html { redirect_to url_exclusions_url, notice: 'Url exclusion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_url_exclusion
    @url_exclusion = UrlExclusion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def url_exclusion_params
    params.require(:url_exclusion).permit(:url_substring)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="description" content="Stanford University Libraries - Eloader Package Administration" />

  <title>EloaderPkgAdmin</title>
  <link href="https://www.stanford.edu/su-identity/css/su-identity.css" rel="stylesheet">
  <link rel="stylesheet" href="https://sul-cdn.stanford.edu/sul_styles/0.5.0/sul-icons.min.css">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.2/js/jquery.tablesorter.js" %>
  <%= csrf_meta_tags %>
  <%= content_for(:head) %>
  <!--[if lt IE 9]> <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
  <!--[if IE 8]> <link rel="stylesheet" type="text/css" href="https://www.stanford.edu/su-identity/css/ie/ie8.css" /> <![endif]-->
  <!--[if IE 7]> <link rel="stylesheet" type="text/css" href="https://www.stanford.edu/su-identity/css/ie/ie7.css" /> <![endif]-->
</head>
<body>
  <div id="su-wrap"> <!-- #su-wrap start -->
    <div id="su-content"> <!-- #su-content start -->
      <div id="outer-container" class="container-fluid">
        <%= render 'shared/top_navbar' %>
        <section id="main-container" role="main">
          <h2><%= controller.page_title %></h2>
          <%= render 'shared/flashes' %>
          <%= render 'shared/nav_buttons' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <%= render 'shared/sul_footer' %>
</body>
</html>

app/views/shared/_flashes.html.erb
<% if [flash[:success], flash[:notice], flash[:warning], flash[:error]].any? %>
  <div class="flashes">
    <% if flash[:success] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:success] %>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:warning] %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:warning] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= flash[:error] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_nav_buttons.html.erb
<div class ='nav-buttons'>
  <ul class='nav nav-pills'>
    <li role="presentation"><%= link_to 'Add package', new_package_path, class: 'btn btn-md btn-default btn-full' %></li>
    <li role="presentation"><%= link_to 'View packages', root_path, class: 'btn btn-md btn-default btn-full' %></li>
    <li role="presentation"><%= link_to 'Exclude Url List', url_exclusions_path, class: 'btn btn-md btn-default btn-full' %></li>
  </ul>
</div>

app/views/shared/_sul_footer.html.erb
<footer role="“contentinfo”">
  <div id="sul-footer-container">
    <div id="sul-footer">
      <div id="sul-footer-img" class="span2">
        <%= image_tag "SUL-logo-stacked.png", alt: "", height: 45 %>
      </div>
      <div id="sul-footer-links" class="span2">
        <ul>
          <li><a href="http://library.stanford.edu">Stanford University Libraries</a></li>
          <li><a href="http://library.stanford.edu/hours">Hours &amp; locations</a></li>
          <li> <a href="http://library.stanford.edu/myawrap.html">My Account</a></li>
          <li> <a href="http://library.stanford.edu/ask">Ask us</a></li>
          <li> <a href="http://library.stanford.edu/opt-out">Opt out of analytics</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<!-- Global footer snippet start -->
<div id="global-footer">
  <div class="container">
    <div class="row">
      <div id="bottom-logo" class="span2">
        <a href="http://www.stanford.edu">
          <img src="https://www.stanford.edu/su-identity/images/footer-stanford-logo@2x.png" alt="Stanford University" width="105" height="49"/>
        </a>
      </div>
      <!-- #bottom-logo end -->
      <div id="bottom-text" class="span10">
        <ul>
          <li class="home"><a href="http://www.stanford.edu">SU Home</a></li>
          <li class="maps alt"><a href="http://visit.stanford.edu/plan/maps.html">Maps &amp; Directions</a></li>
          <li class="search-stanford"><a href="http://www.stanford.edu/search/">Search Stanford</a></li>
          <li class="terms alt"><a href="http://www.stanford.edu/site/terms.html">Terms of Use</a></li>
          <li class="emergency-info"><a href="http://emergency.stanford.edu">Emergency Info</a></li>
        </ul>
      </div> <!-- .bottom-text end -->
      <div class="clear"></div>
      <p class="copyright vcard">&copy; <span class="fn org">Stanford University</span>, <span class="adr"> <span class="locality">Stanford</span>, <span class="region">California</span> <span class="postal-code">94305</span></span>.&nbsp;&nbsp;
      <span id="copyright-complaint"><a href="http://www.stanford.edu/group/security/dmca.html" class="copyright-complaint" >Copyright Complaints</a></span>
      </p>
    </div> <!-- .row end -->
  </div> <!-- .container end -->
</div> <!-- global-footer end -->
<!-- Global footer snippet end -->

app/views/shared/_top_navbar.html.erb
<div id="topnav-container">
  <header id="topnav" class="header-logo" role="banner">
    <%= link_to 'http://library.stanford.edu' do %>
      <%= content_tag :span, "Stanford University Libraries", class: "sr-only" %>
      <%= image_tag "sul-logo.png", class: "hidden-xs", alt: "", height: 25 %>
      <%= image_tag "sul-logo-small.png", class: "visible-xs", alt: "", height: 25 %>
    <% end %>

    <div class="header-links">
      <% if current_user %>
        <%= link_to "#{sunet_id}: Logout", logout_path(referrer: root_path) %>
      <% else %>
        <%= link_to "Login here", login_path(referrer: request.original_url) %>
      <% end %>
    </div>

  </header>
</div>

<div class="topnav-divider">
</div>

app/views/url_exclusions/_form.html.erb
<%= form_for(@url_exclusion) do |f| %>
  <% if @url_exclusion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url_exclusion.errors.count, "error") %> prohibited this url_exclusion from being saved:</h2>

      <ul>
      <% @url_exclusion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_substring, 'String to exclude from URL:' %><br>
    <%= link_to 'Show', @url_exclusion, class: 'btn btn-sm btn-default' %>
    <%= f.text_field :url_substring, size: 80 %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-sm btn-primary' %>
  </div>
<% end %>

app/views/url_exclusions/edit.html.erb
<h3>Editing Url Exclusion <span class='label label-info'>ID <%= @url_exclusion.id %></span></h3>

<%= render 'form' %>

<div class='actions'>
  <%= link_to 'Back', url_exclusions_path %>
</div>

app/views/url_exclusions/index.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th><strong>Excluded URL text</strong></th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @url_exclusions.each do |url_exclusion| %>
      <tr>
        <td class='label label-info'><%= url_exclusion.id %></td>
        <td><%= url_exclusion.url_substring %></td>
        <td><%= link_to 'show', url_exclusion, class: 'btn btn-sm btn-default' %></td>
        <td><%= link_to 'edit', edit_url_exclusion_path(url_exclusion), class: 'btn btn-sm btn-default' %></td>
        <td><%= link_to 'remove', url_exclusion, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url exclusion', new_url_exclusion_path, class: 'btn btn-sm btn-primary btn-full' %>

app/views/url_exclusions/new.html.erb
<h1>New Url Exclusion</h1>

<%= render 'form' %>

<%= link_to 'Back', url_exclusions_path %>

app/views/url_exclusions/show.html.erb
<p>
  <thead>String to exclude</thead>
  <table>
    <tr>
      <td class='label label-info'>
        ID <%= @url_exclusion.id %>
      </td>
      <td><%= @url_exclusion.url_substring %></td>
      <td><%= link_to 'Edit', edit_url_exclusion_path(@url_exclusion), class: 'btn btn-sm btn-default' %></td>
    </tr>
  </table>
</p>